"""
servo heartbeat — slice 011-01 (discover-and-inbox)

The scheduled front-end of the servo loop. A Routine (cron / scheduled agent
/ CI `schedule:`) wakes servo on an interval; this helper's `discover`
subcommand does a **strictly read-only** pass over the target's own signals —
CI failures (`gh`), open issues (`gh`), recent commits (`git`) — and writes
the findings to `<target>/.servo/triage/inbox.jsonl` (one JSON record per
finding) plus a generated, human-readable `<target>/.servo/triage/inbox.md`
view. The pass mutates nothing outside `.servo/triage/`.

Each source degrades independently: a missing `gh`, an auth error, or one
source emitting unparseable JSON skips *that source* with a stderr breadcrumb
and continues over the rest — discovery never hard-fails because one signal is
unavailable. External tools (`gh`, `git`) are invoked via subprocess with
list-form argv (never `shell=True`, never imported), so target-controlled
content (issue titles, commit messages) can never be shell-interpreted; all
subprocess output is treated as untrusted DATA.

Subcommands mirror the house pattern (`gate.py invoke/audit`,
`loop.py`/`hook.py` verbs). Only `discover` ships in 011-01; `dispatch`
(011-03), `run` (011-04), and `status` (011-02) are later slices and are not
implemented here.

Usage:
    python3 heartbeat.py discover <target>

Both artifacts are written atomically — full payload to `<name>.tmp`, then
`os.replace` onto the final path (ADR-0004's house discipline for `.servo/`
state files) — so a SIGTERM/crash mid-write can never leave a torn artifact.
Closed `{0, 2}` exit contract: 0 = discovery completed (zero or more findings,
including the all-sources-skipped case); 2 = environment error that prevents
writing at all (`target_missing` / `target_not_directory` /
`triage_dir_unwritable`). There is **no exit 1** — discovery does not gate.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# JSON record schema version for every line of `inbox.jsonl`. Mirrors
# gate.py's `schema_version` (ADR-0002) and loop.py's state framing. Bump on
# any field rename, type change, or semantic shift; pure additive changes MAY
# keep version=1. Always emitted as the FIRST key of each record.
SCHEMA_VERSION = 1

# Closed exit-code contract (AC4), aligned with gate.py / loop.py but with a
# narrower set — discovery never gates, so there is no "below threshold":
#   0 — discovery completed (zero or more findings; all-skipped is still 0)
#   2 — env error preventing any write (target_missing / target_not_directory
#       / triage_dir_unwritable)
# 1 is intentionally unused.
EXIT_OK = 0
EXIT_ENV_ERROR = 2

# Source identifiers (the closed v1 signal set; the dispatch table below is
# the documented extension point for more sources later).
SOURCE_CI = "ci"
SOURCE_ISSUE = "issue"
SOURCE_COMMIT = "commit"

# Finding status. Every finding at first sight in this slice is "open"; the
# status lifecycle (open → tried → passed/skipped) is 011-02.
STATUS_OPEN = "open"

# Reserved triage artifact dir + filenames, beside `runs/` and `races/`.
TRIAGE_DIRNAME = "triage"
INBOX_JSONL_NAME = "inbox.jsonl"
INBOX_MD_NAME = "inbox.md"

# Atomic-write staging suffix (mirrors loop.py's STATE_TMP_SUFFIX): write the
# full payload here, then os.replace onto the final path.
TMP_SUFFIX = ".tmp"

# Generated-view marker (the `status-board` generated-view convention).
GENERATED_MARKER = "<!-- generated by heartbeat.py — do not hand-edit -->"

# Unit separator delimiting `<sha><US><subject>` in the `git log --pretty`
# format. ASCII 0x1f never appears in a commit sha or (practically) a subject
# line, so it is a safe, parse-stable field delimiter — and avoids any risk of
# a commit message containing the delimiter we'd otherwise pick.
GIT_LOG_FORMAT_TOKEN = "%H%x1f%s"

# How many recent commits / failed runs / issues to enumerate. Bounded so an
# unattended discovery pass over a busy repo stays cheap and the inbox stays
# reviewable. Tunable later (flagged for 011-02 alongside "what's actionable").
COMMIT_LIMIT = 20
CI_RUN_LIMIT = 20
ISSUE_LIMIT = 50

# Bound every subprocess so a wedged `gh` / `git` can never hang an unattended
# heartbeat forever (mirrors gate.py / loop.py's bounded-subprocess
# discipline). 60s is generous for a single network-backed `gh` list call.
SUBPROCESS_TIMEOUT_SECONDS = 60

# `gh run list --json` field surface (verified live, gh 2.92.0). We request
# only the fields this slice reads; the full surface is documented in the
# slice for the next slice's reference.
_GH_RUN_FIELDS = "workflowName,headBranch,conclusion,url,displayTitle,event,createdAt"

# `gh issue list --json` field surface (verified live, gh 2.92.0).
_GH_ISSUE_FIELDS = "number,title,body,url,state,labels,author,createdAt,updatedAt"


def _now_iso() -> str:
    """Current UTC time as an ISO-8601 string (matches loop.py's stamps)."""
    return datetime.now(timezone.utc).isoformat()


def _fingerprint(*parts: str) -> str:
    """Stable 16-hex-char fingerprint over content-identifying parts (AC8).

    `sha256("<part0>|<part1>|...")[:16]`. Derived ONLY from stable,
    content-identifying fields — never timestamps, run ordinals, or attempt
    numbers — so re-running `discover` on identical signals yields identical
    ids. This is the identity 011-02 will dedupe on; 011-01 only computes and
    records it.
    """
    joined = "|".join(parts)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()[:16]


def _run_subprocess(
    argv: list[str], *, cwd: Optional[Path] = None,
) -> tuple[Optional[str], Optional[str]]:
    """Run `argv` (list-form, no shell) bounded by a timeout.

    Returns `(stdout, None)` on a clean exit-0, or `(None, breadcrumb)` on any
    failure: binary absent (FileNotFoundError), non-zero exit, timeout, or
    OSError. The breadcrumb is a single-line, stderr-suitable cause string.

    List-form argv with no `shell=True` means target-controlled content (issue
    titles, commit messages, branch names) is never shell-interpreted — it is
    inert data on the argv, and the *output* is likewise treated as data by the
    callers. The bounded timeout mirrors gate.py / loop.py so a wedged tool
    can't hang an unattended pass.
    """
    try:
        proc = subprocess.run(
            argv,
            cwd=str(cwd) if cwd is not None else None,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=SUBPROCESS_TIMEOUT_SECONDS,
        )
    except FileNotFoundError:
        # Binary not on PATH — execvp raises this before the child runs.
        return None, f"{argv[0]} not on PATH"
    except subprocess.TimeoutExpired:
        return None, f"{argv[0]} timed out after {SUBPROCESS_TIMEOUT_SECONDS}s"
    except OSError as exc:
        return None, f"OS error invoking {argv[0]}: {exc}"
    if proc.returncode != 0:
        return None, f"{argv[0]} exited {proc.returncode}"
    return proc.stdout, None


def _discover_ci(target: Path) -> tuple[Optional[list[dict]], Optional[str]]:
    """Enumerate recent failed CI runs via `gh run list` (AC1a).

    Returns `(findings, None)` on success or `(None, breadcrumb)` when `gh`
    is absent / errors / emits unparseable JSON (AC4 — caller skips just this
    source). One `gh` call per source (no second `gh run view` for jobs — see
    the slice deviation log: `gh run list` has no `job` field, so ci is
    fingerprinted on workflowName + headBranch; job-granularity is deferred to
    011-02 if wanted).
    """
    argv = [
        "gh", "run", "list",
        "--status", "failure",
        "--limit", str(CI_RUN_LIMIT),
        "--json", _GH_RUN_FIELDS,
    ]
    stdout, err = _run_subprocess(argv, cwd=target)
    if err is not None:
        return None, err
    # A clean exit-0 with empty/whitespace stdout means "ran, found nothing" —
    # treat it as an empty list, NOT a parse failure, so the per-source health
    # header reports `ran (0 findings)` rather than mislabeling a healthy
    # source `skipped (unparseable JSON)`. Real `gh --json` emits `[]`, but
    # guarding the empty-stdout edge keeps the AC5 health signal honest.
    raw = (stdout or "").strip()
    if not raw:
        runs = []
    else:
        try:
            runs = json.loads(raw)
        except json.JSONDecodeError as exc:
            return None, f"gh run list emitted unparseable JSON: {exc.msg}"
    if not isinstance(runs, list):
        return None, "gh run list JSON is not a list"

    findings: list[dict] = []
    for run in runs:
        if not isinstance(run, dict):
            continue
        workflow = str(run.get("workflowName", "") or "")
        branch = str(run.get("headBranch", "") or "")
        url = str(run.get("url", "") or "")
        display = str(run.get("displayTitle", "") or "")
        conclusion = str(run.get("conclusion", "") or "")
        title = f"CI failure: {workflow} on {branch}" if workflow else "CI failure"
        detail_parts = []
        if display:
            detail_parts.append(display)
        if conclusion:
            detail_parts.append(f"conclusion={conclusion}")
        findings.append(_build_finding(
            source=SOURCE_CI,
            finding_id=_fingerprint(SOURCE_CI, workflow, branch),
            title=title,
            detail=" — ".join(detail_parts),
            evidence={
                "run_url": url,
                "workflow": workflow,
                "branch": branch,
            },
        ))
    return findings, None


def _discover_issues(target: Path) -> tuple[Optional[list[dict]], Optional[str]]:
    """Enumerate open issues via `gh issue list` (AC1b).

    Returns `(findings, None)` or `(None, breadcrumb)` on absence / error /
    unparseable JSON. Fingerprinted on the issue `number` (AC8).
    """
    argv = [
        "gh", "issue", "list",
        "--state", "open",
        "--limit", str(ISSUE_LIMIT),
        "--json", _GH_ISSUE_FIELDS,
    ]
    stdout, err = _run_subprocess(argv, cwd=target)
    if err is not None:
        return None, err
    # Empty/whitespace stdout on a clean exit-0 = "ran, found nothing" → empty
    # list, not a parse failure (mirrors _discover_ci; keeps the AC5 health
    # header from mislabeling a healthy-but-empty source `skipped`).
    raw = (stdout or "").strip()
    if not raw:
        issues = []
    else:
        try:
            issues = json.loads(raw)
        except json.JSONDecodeError as exc:
            return None, f"gh issue list emitted unparseable JSON: {exc.msg}"
    if not isinstance(issues, list):
        return None, "gh issue list JSON is not a list"

    findings: list[dict] = []
    for issue in issues:
        if not isinstance(issue, dict):
            continue
        number = issue.get("number")
        if number is None:
            continue
        title = str(issue.get("title", "") or "")
        url = str(issue.get("url", "") or "")
        body = str(issue.get("body", "") or "")
        # Trim the body for the detail field — the inbox is reviewable, not an
        # issue mirror; the full issue lives behind the url. (The body is also
        # untrusted attacker-influenceable text per guardrail #4, inert here in
        # 011-01 but kept short regardless.)
        detail = body.strip().splitlines()[0][:200] if body.strip() else ""
        findings.append(_build_finding(
            source=SOURCE_ISSUE,
            finding_id=_fingerprint(SOURCE_ISSUE, str(number)),
            title=title,
            detail=detail,
            evidence={
                "issue_number": number,
                "url": url,
            },
        ))
    return findings, None


def _discover_commits(target: Path) -> tuple[Optional[list[dict]], Optional[str]]:
    """Enumerate recent commits via `git log` (AC1c).

    Returns `(findings, None)` or `(None, breadcrumb)` on absence / error.
    Uses a unit-separator-delimited `--pretty` format so each line parses into
    `<sha><US><subject>` deterministically. Fingerprinted on the commit sha
    (AC8). (What makes a commit-finding *actionable* is an open question
    deferred to 011-02; 011-01 records every recent commit `open`.)
    """
    argv = [
        "git", "-C", str(target), "log",
        f"--max-count={COMMIT_LIMIT}",
        f"--pretty=format:{GIT_LOG_FORMAT_TOKEN}",
    ]
    stdout, err = _run_subprocess(argv)
    if err is not None:
        # Distinct breadcrumb wording so a reader can tell git-log-failed apart
        # from gh-absent (AC4).
        return None, f"git log failed ({err})"

    findings: list[dict] = []
    for line in (stdout or "").splitlines():
        if not line.strip():
            continue
        sha, _, subject = line.partition("\x1f")
        sha = sha.strip()
        if not sha:
            continue
        findings.append(_build_finding(
            source=SOURCE_COMMIT,
            finding_id=_fingerprint(SOURCE_COMMIT, sha),
            title=subject.strip() or sha,
            detail=f"commit {sha[:12]}",
            evidence={"commit_sha": sha},
        ))
    return findings, None


def _build_finding(
    *, source: str, finding_id: str, title: str, detail: str, evidence: dict,
) -> dict:
    """Construct one finding record (AC3) with schema_version as the first key.

    Key insertion order is load-bearing: `schema_version` first (mirrors
    gate.py / loop.py / ADR-0004), then the stable identity + content fields,
    then `discovered_at` (volatile — never part of the fingerprint) and the
    always-`open` status.
    """
    return {
        "schema_version": SCHEMA_VERSION,
        "finding_id": finding_id,
        "source": source,
        "title": title,
        "detail": detail,
        "evidence": evidence,
        "discovered_at": _now_iso(),
        "status": STATUS_OPEN,
    }


# Discovery dispatch table (the documented extension point for more sources,
# same shape as the oracle component registry). Each entry maps a source id to
# its enumerator; `discover` walks the table in order so the inbox grouping is
# deterministic.
_DISCOVERY_SOURCES = (
    (SOURCE_CI, _discover_ci),
    (SOURCE_ISSUE, _discover_issues),
    (SOURCE_COMMIT, _discover_commits),
)


def _atomic_write(path: Path, payload: str) -> None:
    """Write `payload` to `path` atomically (ADR-0004's atomic-write contract).

    Writes the full payload to `<name>.tmp`, then `os.replace`s onto the final
    path. `os.replace` is atomic on POSIX and NTFS, so a Ctrl-C / SIGTERM /
    power loss mid-write can never leave a torn artifact for the next reader or
    the next heartbeat. (Single-writer torn-write safety only; concurrent
    multi-writer locking for a double-fired Routine is deferred to 011-02.)
    """
    tmp = path.with_name(path.name + TMP_SUFFIX)
    tmp.write_text(payload)
    os.replace(tmp, path)


def _render_jsonl(findings: list[dict]) -> str:
    """Serialize findings to JSONL — one JSON object per line."""
    if not findings:
        return ""
    return "\n".join(json.dumps(f) for f in findings) + "\n"


def _render_markdown(
    findings: list[dict], source_status: dict[str, dict], target: Path,
) -> str:
    """Render the human-reviewable `inbox.md` view (AC5).

    Opens with the generated-view marker and a per-source status header (each
    source `ran` + finding count, or `skipped` + cause), THEN the findings
    grouped by source, each showing title + status + an evidence ref. The
    header makes a silently-degraded unattended run (e.g. a missing `gh` auth
    surfacing an empty-looking inbox) visible in the artifact a human reviews —
    not only in the stderr breadcrumb.
    """
    lines: list[str] = []
    lines.append(GENERATED_MARKER)
    lines.append("")
    lines.append(f"# servo triage inbox — {target.name}")
    lines.append("")
    lines.append(f"_Discovered at {_now_iso()}._")
    lines.append("")
    lines.append("## Source status")
    lines.append("")
    for source, _enum in _DISCOVERY_SOURCES:
        info = source_status.get(source, {})
        if info.get("ran"):
            count = info.get("count", 0)
            lines.append(f"- **{source}**: ran ({count} finding"
                         f"{'' if count == 1 else 's'})")
        else:
            cause = info.get("cause", "unknown")
            lines.append(f"- **{source}**: skipped ({cause})")
    lines.append("")

    total = len(findings)
    lines.append(f"## Findings ({total})")
    lines.append("")
    if total == 0:
        lines.append("_No findings this pass._")
        lines.append("")
        return "\n".join(lines) + "\n"

    for source, _enum in _DISCOVERY_SOURCES:
        group = [f for f in findings if f["source"] == source]
        if not group:
            continue
        lines.append(f"### {source} ({len(group)})")
        lines.append("")
        for f in group:
            ref = _evidence_ref(f)
            title = f.get("title", "") or "(untitled)"
            lines.append(f"- [{f['status']}] {title}" + (f" — {ref}" if ref else ""))
            # Render the detail beneath the title when present — for a CI
            # finding this surfaces the run's displayTitle/conclusion, which is
            # what a reviewer scans to triage "is this worth a loop?". Kept on
            # its own indented line so the title line stays a clean one-liner.
            detail = (f.get("detail", "") or "").strip()
            if detail:
                lines.append(f"  - {detail}")
        lines.append("")
    return "\n".join(lines) + "\n"


def _evidence_ref(finding: dict) -> str:
    """Pick a single human-facing evidence reference (URL or sha) for a finding."""
    ev = finding.get("evidence", {})
    if not isinstance(ev, dict):
        return ""
    for key in ("url", "run_url"):
        val = ev.get(key)
        if val:
            return str(val)
    sha = ev.get("commit_sha")
    if sha:
        return str(sha)
    number = ev.get("issue_number")
    if number is not None:
        return f"#{number}"
    return ""


def _emit_breadcrumb(message: str) -> None:
    """Write a single-line `heartbeat: ...` breadcrumb to stderr."""
    sys.stderr.write(f"heartbeat: {message}\n")


def run_discover(target: Path) -> int:
    """Read-only discovery pass over the three signal families (AC1).

    Validates the target, bootstraps `<target>/.servo/triage/` (AC9), walks
    the discovery dispatch table degrading each source independently (AC4),
    and atomically writes `inbox.jsonl` + `inbox.md` (AC2/AC5). Returns the
    closed `{0, 2}` exit code (AC4): 2 only on an env error that prevents
    writing at all; 0 in every other case, including all-sources-skipped.
    """
    # ---- Env preconditions (the only paths that exit 2) --------------------
    if not target.exists():
        _emit_breadcrumb(f"target does not exist: {target} (target_missing)")
        return EXIT_ENV_ERROR
    if not target.is_dir():
        _emit_breadcrumb(
            f"target is not a directory: {target} (target_not_directory)"
        )
        return EXIT_ENV_ERROR

    # ---- Triage dir bootstrap (AC9) ----------------------------------------
    triage_dir = target / ".servo" / TRIAGE_DIRNAME
    try:
        triage_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        _emit_breadcrumb(
            f"cannot create triage dir {triage_dir}: {exc} (triage_dir_unwritable)"
        )
        return EXIT_ENV_ERROR

    # ---- Oracle-independence breadcrumb (AC9) ------------------------------
    # Discovery is oracle-INDEPENDENT: it never refuses on a missing oracle.
    # It records a breadcrumb noting dispatch will be unavailable until the
    # target is scaffolded (the oracle gate lives at dispatch, 011-03).
    manifest = target / ".servo" / "install.json"
    oracle = target / "oracle.sh"
    if not manifest.exists() or not oracle.exists():
        _emit_breadcrumb(
            f"no oracle/manifest at {target} — discovery only; "
            f"dispatch unavailable until /servo:scaffold-init"
        )

    # ---- Walk the discovery dispatch table (AC1/AC4) -----------------------
    findings: list[dict] = []
    source_status: dict[str, dict] = {}
    skipped_sources: list[str] = []
    for source, enumerator in _DISCOVERY_SOURCES:
        source_findings, err = enumerator(target)
        if err is not None or source_findings is None:
            cause = err or "unknown error"
            source_status[source] = {"ran": False, "cause": cause}
            skipped_sources.append(source)
            # Distinct, source-naming stderr breadcrumb (AC4).
            _emit_breadcrumb(f"{cause} — skipping {source} source")
            continue
        source_status[source] = {"ran": True, "count": len(source_findings)}
        findings.extend(source_findings)

    # ---- Atomically write both artifacts (AC2/AC5) -------------------------
    jsonl_path = triage_dir / INBOX_JSONL_NAME
    md_path = triage_dir / INBOX_MD_NAME
    try:
        _atomic_write(jsonl_path, _render_jsonl(findings))
        _atomic_write(md_path, _render_markdown(findings, source_status, target))
    except OSError as exc:
        _emit_breadcrumb(
            f"cannot write triage artifacts under {triage_dir}: {exc} "
            f"(triage_dir_unwritable)"
        )
        return EXIT_ENV_ERROR

    # ---- Summary breadcrumb (AC4 — visible even on the all-skipped path) ---
    ran = [s for s, info in source_status.items() if info.get("ran")]
    if not ran:
        _emit_breadcrumb(
            f"all sources skipped ({', '.join(skipped_sources)}); "
            f"wrote empty inbox to {jsonl_path}"
        )
    else:
        _emit_breadcrumb(
            f"discovered {len(findings)} finding"
            f"{'' if len(findings) == 1 else 's'} from {len(ran)} source"
            f"{'' if len(ran) == 1 else 's'} → {jsonl_path}"
        )
    return EXIT_OK


def main(argv: Optional[list[str]] = None) -> int:
    if argv is None:
        argv = sys.argv[1:]

    parser = argparse.ArgumentParser(
        prog="heartbeat.py",
        description=(
            "The scheduled front-end of the servo loop. Subcommands mirror "
            "the house pattern; only `discover` (read-only signal discovery → "
            "triage inbox) ships in slice 011-01. `dispatch` / `run` / "
            "`status` are later slices."
        ),
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    discover_parser = subparsers.add_parser(
        "discover",
        help=(
            "Read-only pass over CI failures (gh), open issues (gh), and "
            "recent commits (git); write findings to "
            "<target>/.servo/triage/inbox.jsonl + a generated inbox.md."
        ),
        description=(
            "Strictly read-only discovery: writes ONLY under "
            "<target>/.servo/triage/. Each source degrades independently — a "
            "missing gh / an auth error / one source failing skips that source "
            "with a stderr breadcrumb and continues. Closed {0,2} exit "
            "contract: 0 = completed (zero or more findings); 2 = env error "
            "preventing any write."
        ),
    )
    discover_parser.add_argument(
        "target",
        type=Path,
        help="Path to the target project (discovery is oracle-independent).",
    )

    args = parser.parse_args(argv)

    if args.command == "discover":
        return run_discover(args.target.resolve())

    # argparse `required=True` guarantees a known subcommand; this is a
    # defensive fallback only.
    parser.error(f"unknown command: {args.command}")
    return EXIT_ENV_ERROR  # unreachable — parser.error exits


if __name__ == "__main__":
    sys.exit(main())
